using AttendenceManagementSystem.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System;

namespace AttendenceManagementSystem.Data
{
    public static class SeedData
    {
        public static async Task Initialize(IServiceProvider serviceProvider)
        {
            var context = serviceProvider.GetRequiredService<ApplicationDbContext>();
            var userManager = serviceProvider.GetRequiredService<UserManager<ApplicationUser>>();
            var roleManager = serviceProvider.GetRequiredService<RoleManager<IdentityRole>>();

            // 1. Ensure database is created
            await context.Database.EnsureCreatedAsync();

            // 2. Seed roles
            string[] roleNames = { "Admin", "Teacher", "Student" };
            foreach (var roleName in roleNames)
            {
                if (!await roleManager.RoleExistsAsync(roleName))
                {
                    await roleManager.CreateAsync(new IdentityRole(roleName));
                }
            }

            // 3. Seed Admin User
            var adminUser = await userManager.FindByEmailAsync("admin@university.com");
            if (adminUser == null)
            {
                adminUser = new ApplicationUser
                {
                    UserName = "admin@university.com",
                    Email = "admin@university.com",
                    FullName = "System Administrator",
                    EmailConfirmed = true
                };

                var result = await userManager.CreateAsync(adminUser, "Admin123!");
                if (result.Succeeded)
                {
                    await userManager.AddToRoleAsync(adminUser, "Admin");
                }
            }

            // 4. Seed Departments, Batches, Sections, Courses, Teachers, Timetables
            await SeedSampleData(context, userManager);
        }

        private static async Task SeedSampleData(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            // --- Departments ---
            var csDept = await context.Departments.FirstOrDefaultAsync(d => d.Code == "CS");
            if (csDept == null)
            {
                csDept = new Department { Name = "Computer Science", Code = "CS" };
                context.Departments.Add(csDept);
                await context.SaveChangesAsync();
            }

            // --- Batches ---
            var batch2023 = await context.Batches.FirstOrDefaultAsync(b => b.Year == "2023" && b.DepartmentId == csDept.Id);
            if (batch2023 == null)
            {
                batch2023 = new Batch { Year = "2023", DepartmentId = csDept.Id, Description = "CS Batch 2023" };
                context.Batches.Add(batch2023);
                await context.SaveChangesAsync();
            }

            // --- Sections ---
            var sectionA = await context.Sections.FirstOrDefaultAsync(s => s.Name == "A" && s.BatchId == batch2023.Id);
            if (sectionA == null)
            {
                sectionA = new Section { Name = "A", BatchId = batch2023.Id };
                context.Sections.Add(sectionA);
                await context.SaveChangesAsync();
            }

            // --- Teacher User & Entity (Required for Timetable) ---
            var teacherEmail = "teacher@university.com";
            var teacherUser = await userManager.FindByEmailAsync(teacherEmail);
            if (teacherUser == null)
            {
                teacherUser = new ApplicationUser
                {
                    UserName = teacherEmail,
                    Email = teacherEmail,
                    FullName = "Dr. Alan Turing",
                    EmailConfirmed = true
                };
                var res = await userManager.CreateAsync(teacherUser, "Teacher123!");
                if (res.Succeeded) await userManager.AddToRoleAsync(teacherUser, "Teacher");
            }
            
            // Re-fetch to get the ID generated by DB
            teacherUser = await userManager.FindByEmailAsync(teacherEmail);
            
            var teacherEntity = await context.Teachers.FirstOrDefaultAsync(t => t.UserId == teacherUser.Id);
            if (teacherEntity == null)
            {
                teacherEntity = new Teacher
                {
                    UserId = teacherUser.Id,
                    FullName = "Dr. Alan Turing",
                    DepartmentId = csDept.Id,
                    EmployeeId = "EMP001",
                    IsApproved = true,
                    IsActive = true
                };
                context.Teachers.Add(teacherEntity);
                await context.SaveChangesAsync();
            }

            // --- Courses (WITH SEMESTERS) ---
            if (!await context.Courses.AnyAsync(c => c.Code == "CS101"))
            {
                context.Courses.AddRange(
                    new Course { Code = "CS101", Title = "Introduction to Programming", DepartmentId = csDept.Id, Credits = 3, Semester = "FALL 2025" },
                    new Course { Code = "CS102", Title = "Data Structures", DepartmentId = csDept.Id, Credits = 4, Semester = "FALL 2025" },
                    new Course { Code = "CS201", Title = "Database Systems", DepartmentId = csDept.Id, Credits = 3, Semester = "SPRING 2026" }
                );
                await context.SaveChangesAsync();
            }
            else
            {
                // Fix existing courses that might have empty semesters
                var coursesToFix = await context.Courses.Where(c => c.Semester == null || c.Semester == "").ToListAsync();
                foreach(var c in coursesToFix)
                {
                    c.Semester = "FALL 2025";
                }
                if (coursesToFix.Any()) await context.SaveChangesAsync();
            }

            // --- Timetable (Link Course + Section + Teacher) ---
            var courseCS101 = await context.Courses.FirstOrDefaultAsync(c => c.Code == "CS101");
            
            if (courseCS101 != null && teacherEntity != null && sectionA != null && batch2023 != null)
            {
                if (!await context.Timetables.AnyAsync(t => t.CourseId == courseCS101.Id && t.SectionId == sectionA.Id))
                {
                    context.Timetables.Add(new Timetable
                    {
                        CourseId = courseCS101.Id,
                        TeacherId = teacherEntity.Id,
                        SectionId = sectionA.Id,
                        BatchId = batch2023.Id,
                        DayOfWeek = DayOfWeek.Monday,
                        StartTime = new TimeSpan(9, 0, 0),
                        EndTime = new TimeSpan(10, 30, 0)
                    });
                    await context.SaveChangesAsync();
                }
            }
        }
    }
}